#!/bin/bash


# Script to automate John's dev environment setup
# Needs to work inside WSL AND on actual linux
# Needs to work on Ubuntu (work )and Arch (personal)

set -ex

setup_ansible() {
  DEBIAN_FRONTEND=noninteractive sudo apt-get -y update
  DEBIAN_FRONTEND=noninteractive sudo apt-get -y install python-is-python3 ansible
}


setup_ansible_deps() {
  ansible-galaxy install -r requirements.yml
}

setup_using_ansible() {
  ansible-playbook -i,localhost site.yml
}

setup_ansible

# Commented, since this is not necessary and will not work until network issues caused by corporate laptop are fixed
#setup_ansible_deps
setup_using_ansible
