#=============================================================================
# dark_powered.toml --- dark powered configuration example for SpaceVim
# Copyright (c) 2016-2021 Wang Shidong & Contributors
# Author: Wang Shidong < wsdjeg at 163.com >
# URL: https://spacevim.org
# License: GPLv3
#=============================================================================

# All SpaceVim option below [option] section
[options]
# set spacevim theme. by default colorscheme layer is not loaded,
# if you want to use more colorscheme, please load the colorscheme
# layer
colorscheme = "NeoSolarized"
colorscheme_bg = "dark"
# Disable guicolors in basic mode, many terminal do not support 24bit
# true colors
enable_guicolors = true
# Disable statusline separator, if you want to use other value, please
# install nerd fonts

#statusline_separator = "arrow"
#statusline_iseparator = "arrow"
buffer_index_type = 4
enable_tabline_filetype_icon = true
#enable_statusline_mode = false

# JC
filemanager = "nerdtree"
filetree_direction = 'left'
wildignore = "*/build/*"
#enable_filetree_gitstatus = true
#vimcompatible = true
bootstrap_before = "myspacevim#before"
bootstrap_after = "myspacevim#after"

# Enable autocomplete layer
[[layers]]
name = 'autocomplete'
auto_completion_return_key_behavior = "complete"
auto_completion_tab_key_behavior = "smart"

[[layers]]
name = 'shell'
default_position = 'top'
default_height = 30

[[layers]]
name = "lang#python"
python_interpreter = '/home/john/.pyenv/versions/{{ spacevim_virtualenv_name }}/bin/python'
#enabled_linters = ['pylint', 'mypy']
#enable_typeinfo = true

[[layers]]

name = "lsp"
enabled_clients = ["pyright"]
filetypes = [
  "python"
]

[[layers]]
name = "colorscheme"

[[layers]]
name = "test"

[[layers]]
name = "VersionControl"

[[layers]]
name = "git"

[[layers]]
name = "github"

[[layers]]
name = "edit"

[[layers]]
name = "fzf"

[[layers]]
name = "default"
# Can't find for some reason

[[layers]]
name = "tools"

[[layers]]
name = "vim"

[[layers]]
name = "checkers"

show_cursor_error = true

[[layers]]
name = "lang#vue"

[[layers]]
name = "lang#javascript"

[[layers]]
name = "lang#typescript"

[[layers]]
name = "lang#sql"

# [[custom_plugins]]
# name = "vim-scripts/dbext.vim"
# merged = 0

# [[custom_plugins]]
# repo = "github/copilot.vim"
# merged = false
#
