---

- name: Install pyenv
  shell: curl https://pyenv.run | bash

- name: pyenv .bashrc .profile etc.
  lineinfile:
    path: "{{ item[0] }}"
    line: "{{ item[1] }}"
  loop: "{{ files | product(lines) | list }}"
  vars:
    files:
      - "{{ pyenv_user_home_dir }}/.bashrc"
      - "{{ pyenv_user_home_dir }}/.profile"
    lines:
      - export PYENV_ROOT="$HOME/.pyenv"
      - command -v pyenv >/dev/null || export PATH="$PYENV_ROOT/bin:$PATH"
      - eval "$(pyenv init -)"

- name: Python build deps
  become: yes
  become_user: root
  apt:
    pkg:
      - libssl-dev
      - zlib1g-dev
      - libbz2-dev
      - libreadline-dev
      - libsqlite3-dev
      - curl
      - libncursesw5-dev
      - xz-utils
      - tk-dev
      - libxml2-dev
      - libxmlsec1-dev
      - libffi-dev
      - liblzma-dev

